car/urls.py
from django.urls import path,include
from . import views

app_name = "car"
urlpatterns =[
    path('home',views.home_page, name='home_page'),
    path('cars',views.cars_page, name='cars_page'),
    path('gallery',views.gallery_page, name='gallery_page'),
    path('contactus',views.contactus_page, name='contactus_page'),
    path('aboutus',views.aboutus_page, name='aboutus_page'),
    path('register',views.register_page, name='register_page'),
    path('login',views.login_page, name='login_page'),
    path('logout',views.logout_page, name='logout_page'),
    # path('login_view',views.login_view_page, name='login_view_page'),
    path('dashboard',views.dashboard_page, name='dashboard_page'),

           
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('car/',  include("car.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

car/models.py
from django.db import models



        
class Car_details(models.Model):
    car_title = models.CharField(max_length=50)
    # city = models.CharField(max_length = 50)
    color = models.CharField(max_length=50)
    # model = models.CharField(max_length=50)
    # year = models.IntegerField()
    price = models.FloatField()
    # mileage = models.IntegerField()
    # description = models.TextField()
    image = models.ImageField(upload_to='photos/%Y/%m/%d/', default=" ")
    def __str__(self):
        return self.car_title
    

# class User_details(models.Model):
#     first_name = models.CharField(max_length=255)
#     last_name = models.CharField(max_length=255)
#     username = models.CharField(max_length=255, unique=True)
#     email = models.EmailField(max_length=255, unique=True)
#     date_of_birth = models.DateField(null=True, blank=True)
#     profile_picture = models.ImageField(upload_to='profile_pics/', null=True, blank=True)
#     password = models.CharField(max_length=255)
#     phone_number = models.CharField(max_length=20)
#     address = models.CharField(max_length=255)
#     city = models.CharField(max_length=255)
#     state = models.CharField(max_length=255)
#     pin_code = models.CharField(max_length=20)

#saketh
#Saketh#6

car/views.py
from django.shortcuts import render, redirect
from . models import Car_details
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User

def home_page(request):
    return render(request,'car/home.html')

def cars_page(request):
    car_details = Car_details.objects.all()
    return render(request,'car/cars.html',{'car_details': car_details})

def gallery_page(request):
    return render(request,'car/gallery.html')

def contactus_page(request):
    return render(request,'car/contactus.html')

def aboutus_page(request):
    return render(request,'car/aboutus.html')

def register_page(request):
    if request.method == "POST":
        firstname_ = request.POST.get('firstname','')
        lastname_ = request.POST.get('lastname','')
        username_ = request.POST.get('username','')
        email_ = request.POST.get('Email','')
        password_ = request.POST.get('password','')
        confirm_password_ = request.POST.get('confirm_password','')
        
        if password_ == confirm_password_:
            if User.objects.filter(username = username_).exists():
                messages.error(request, 'username already exists')
                return redirect('car:register_page')
            else:
                if User.objects.filter(email = email_).exists():
                    messages.error(request, 'Email already exists')
                    return redirect('car:register_page')
                else:
                    user = User.objects.create_user(username_,email_,password_)
                    user.first_name = firstname_
                    user.last_name = lastname_
                    user.save()
                   
                    return redirect('car:register_page')
                
    return render(request, 'car/register.html')
        
        
    

def login_page(request):
    if request.method == "POST":
        username_ = request.POST.get('user','')
        password_ = request.POST.get('pass','')
        user = authenticate(request, username = username_, password = password_ )
        if user is not None:
            login(request, user)
            return redirect('car:home_page')
        else:
            return redirect('car:login_page')
    return render(request, 'car/login.html')



def logout_page(request):
    return render(request, 'car/dashboard.html')

def dashboard_page(request):
    return render(request, 'car/dashboard.html')

car/templates/car/aboutus.html
{% extends 'car/base.html'%}

{% block title %}
aboutus_page
{% endblock%}

{% load static %}

{% block content%}
    <h3>About us</h3>
{% endblock content%}

<form action="{% url 'car:register_page' %}" method="POST">
    {% csrf_token %}
    
    <label for="first_name">First Name:</label>
    <input type="text" name="first_name" required><br><br>

    <label for="last_name">Last Name:</label>
    <input type="text" name="last_name" required><br><br>

    <label for="username">Username:</label>
    <input type="text" name="username" required><br><br>

    <label for="email">Email:</label>
    <input type="email" name="email" required><br><br>

    <label for="password">Password:</label>
    <input type="password" name="password" required><br><br>

    <label for="phone_number">Phone Number:</label>
    <input type="tel" name="phone_number" required><br><br>

    <label for="address">Address:</label>
    <input type="text" name="address" required><br><br>

    <label for="city">City:</label>
    <input type="text" name="city" required><br><br>

    <label for="state">State:</label>
    <input type="text" name="state" required><br><br>

    <label for="pin_code">Pin Code:</label>
    <input type="text" name="pin_code" required><br><br>

    <label for="date_of_birth">Date of Birth:</label>
    <input type="date" name="date_of_birth"><br><br>

    <label for="profile_picture">Profile Picture:</label>
    <input type="file" name="profile_picture"><br><br>

    <input type="submit" value="submit">
    
</form>

car/templates/car/base.html
<!doctype html>
<html lang="en">
<head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>RideFinder - {% block title %}   {% endblock%}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'car/source/bootstrap-3.3.6-dist/css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'car/source/font-awesome-4.5.0/css/font-awesome.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'car/style/slider.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'car/style/mystyle.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'car/css/cars.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'car/css/register.css'%}">
    
    

  </head>
  <body>
    <!-- Header -->
    <div class="allcontain">
        <div class="header">

                <ul class="socialicon">
                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                    <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                </ul>
                <ul class="givusacall">
                    
                    <li>RIDE FINDER </li>
                </ul>
    
                <ul class="logreg">

                        <li><a href="{% url 'car:login_page' %}">Login </a> </li>
                        <li><a href="{% url 'car:register_page' %}"><span class="register">Register</span></a></li>
                        <!-- <li><a href="{% url 'car:dashboard_page' %}"><span class="register">Dashboard</span></a></li> -->
                    
                </ul>
        </div>

        <!-- Navbar Up -->
        <nav class="topnavbar navbar-default topnav">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed toggle-costume" data-toggle="collapse" data-target="#upmenu" aria-expanded="false">
                        <span class="sr-only"> Toggle navigaion</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- <a class="navbar-brand logo" href="#"><img src="{% static 'car/image/logo1.png'%}" alt="logo"></a> -->
                </div>	 
            </div>
            <div class="collapse navbar-collapse" id="upmenu">
                <ul class="nav navbar-nav" id="navbarontop">
                    <li class="active"><a href="{% url 'car:home_page' %}">HOME</a> </li>
                    <li class="active"><a href="{% url 'car:cars_page' %}">CARS</a> </li>
                    <li class="active"><a href="{% url 'car:gallery_page' %}">GALLERY</a> </li>
                    <li class="active"><a href="{% url 'car:contactus_page' %}">CONTACT US</a> </li>
                    <li class="active"><a href="{% url 'car:aboutus_page' %}">ABOUT US</a> </li>

                </ul>
            </div>
        </nav>
    </div>
    {% block content%}

    {% endblock content%}
    
    </head>
</html>

car/templates/car/cars.html
{% extends 'car/base.html'%}
{% load static %}

{% block title %}
cars_page
{% endblock%}

{% block content %}

    {% for cars in car_details %}
        <div class="card" style="width: 18rem;">
            <img src="{{ cars.image }}"  class="card-img-top">
            <div class="card-body">
            <h5 class="card-title">Car name : {{cars.car_title}}</h5>
            <h5 class="card-title">Car color : {{cars.color}}</h5>
            
            <a href="#" class="btn btn-primary">Add to dashboard</a>
            </div>
        </div>
    {% endfor %}
  


  {% endblock content %}

car/templates/car/contactus.html
{% extends 'car/base.html'%}

{% block title %}
contact_page
{% endblock%}

{% load static %}

{% block content%}
    <h3>contact us</h3>
{% endblock content%}

car/templates/car/dashboard.html
{% extends 'car/base.html'%}

{% block title %}
dashboard_page
{% endblock%}

{% load static %}
{% block content %}

{% endblock content %}

car/templates/car/gallery.html
{% extends 'car/base.html'%}

{% block title %}
gallery_page
{% endblock%}

{% load static %}

{% block content%}
    <h3>gallery</h3>
{% endblock content%}

car/templates/car/login.html
{% extends 'car/base.html'%}

{% block title %}
Login_page
{% endblock%}

{% load static %}

{% block content%}
<div class="container">
    <br>
    <br>
    
    <div class="box">
        <br>
        <h1 class="top">USER LOGIN</h1>
        <br>
        <p class="caption">RideFinder Login</p>
        <br>
        <hr>
        <br>

        <form action="{% url 'car:login_page' %}" method="POST">
            {% csrf_token %}
            <input id="username" class="mobile" type="text" placeholder="Mobile number or Email address" name="user">
            <br>
            <br>
            <P id="mail_id"> </P>
            <input id="password" class="mobile" type="password" placeholder="Password" name="pass">
            <br>
            <br>
            <p id="pass"> </p>
            <button type="submit" class="sign" >Login</button>
            <br>
            <br>
        </form>
       
           
            

       
        
        
    </div>
    <br><br><br><br>
    
</div>

{% endblock content%}

car/templates/car/login_view.html
<!doctype html>
<html lang="en">
<head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>RideFinder - login_view page</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'car/source/bootstrap-3.3.6-dist/css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'car/source/font-awesome-4.5.0/css/font-awesome.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'car/style/slider.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'car/style/mystyle.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'car/css/cars.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'car/css/register.css'%}">
    
    

  </head>
  <body>
    <!-- Header -->
    <div class="allcontain">
        <div class="header">

                <ul class="socialicon">
                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                    <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                </ul>
                <ul class="givusacall">
                    
                    <li>RIDE FINDER </li>
                </ul>
    
                <ul class="logreg">
                    <li><a href="{% url 'car:dashboard_page' %}">dashboard </a> </li>
                    <li><a href="{% url 'car:register_page' %}"><span class="register">logout</span></a></li>
                    
                </ul>
        </div>

        <!-- Navbar Up -->
        <nav class="topnavbar navbar-default topnav">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed toggle-costume" data-toggle="collapse" data-target="#upmenu" aria-expanded="false">
                        <span class="sr-only"> Toggle navigaion</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- <a class="navbar-brand logo" href="#"><img src="{% static 'car/image/logo1.png'%}" alt="logo"></a> -->
                </div>	 
            </div>
            <div class="collapse navbar-collapse" id="upmenu">
                <ul class="nav navbar-nav" id="navbarontop">
                    <li class="active"><a href="{% url 'car:home_page' %}">HOME</a> </li>
                    <li class="active"><a href="{% url 'car:cars_page' %}">CARS</a> </li>
                    <li class="active"><a href="{% url 'car:gallery_page' %}">GALLERY</a> </li>
                    <li class="active"><a href="{% url 'car:contactus_page' %}">CONTACT US</a> </li>
                    <li class="active"><a href="{% url 'car:aboutus_page' %}">ABOUT US</a> </li>

                </ul>
            </div>
        </nav>
    </div>
    {% block content%}

    {% endblock content%}
    
    </head>
</html>

car/templates/car/messages.html
{% if messages %}

  {% for message in messages %}
      <div id="message" class="container">
        <div class="alert alert-{{ message.tags }}" alert-dismissable role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>

            <strong>
              {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                  Error:
              {% else %}
                  {{message.tags|title}}
              {% endif %}
            </strong>
            {{message}}
        </div>
      </div>
  {% endfor %}

{% endif %}

car/templates/car/register.html
{% extends 'car/base.html'%}

{% block title %}
Register_page
{% endblock%}

{% load static %}
{% block content %}


<form action="{% url 'car:register_page' %}" method="POST">
  {% csrf_token %}
  <div class="box">
    <h1 class="top">Create a new account</h1>
    <p class="caption">It's quick and easy.</p>
    <br>
    <hr>
    <br>
    <input id="first_name" class="first" type="text" placeholder="First name" name="firstname">
    <input id="surname" class="first" type="text" placeholder="last name" name="lastname">
    <br>
    <br>
    <p id="first"></p>
    <input id="email_id" class="mobile" type="text" placeholder="username" name="username">
    <br>
    <br>
    <p id="first"></p>
    <input id="email_id" class="mobile" type="text" placeholder="Email Address" name="Email">
    <br>
    <br>
    <p id="mobile"></p>
    <input id="pass"  class="mobile" type="password" placeholder="New Password" name="password">
    <br>
    <br>
    <p id="mobile"></p>
    <input id="pass"  class="mobile" type="password" placeholder=" Confirm New Password" name=" confirm_password">
    <br>
    <br>
    
    <button type="submit" class="sign" value="submit" >Register</button>
    <p class="end"><a href="{% url  'car:login_page' %}" target="blank">Already have an account?</a></p>
    
</div>
         
</form>

{% endblock content %}